"""Initial migration

Revision ID: 362182dd6f0f
Revises: 
Create Date: 2023-07-25 13:29:55.545242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362182dd6f0f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], name=op.f('fk_lessons_coach_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], name=op.f('fk_sessions_coach_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_bookings_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_bookings_student_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], name=op.f('fk_link_lesson_id_lessons')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_link_session_id_sessions')),
    sa.PrimaryKeyConstraint('session_id', 'lesson_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('link')
    op.drop_table('bookings')
    op.drop_table('sessions')
    op.drop_table('lessons')
    op.drop_table('users')
    # ### end Alembic commands ###
