"""added to booking

Revision ID: 7a335c835094
Revises: e5f7ff3b9d01
Create Date: 2024-02-25 11:32:18.006198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a335c835094'
down_revision = 'e5f7ff3b9d01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_bookings_category_id_categories'), 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint('fk_lessons_category_id_categories', type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_lessons_category_id_categories', 'categories', ['category_id'], ['id'])

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bookings_category_id_categories'), type_='foreignkey')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
